language: python
python:
- '3.6'
install:
- python -m pip install .[dev]
script:
- pytest --flake8 --cov=dnote
after_success:
- coveralls
deploy:
  provider: pypi
  user: yetisir
  password: SH/NEDDH2cjp8O+eyEU0tdgW1GXuakTA+U1/5AaTfr9pIags0khKKaQ07Nicp6/DAQgzLHZY1PVvhb9jKSncyAPHGA0RTnoItc6Ja3SsPGgDb568e9uwaD0hQUJdb8XvbPltyaIYY1q67uickchv2Lnk5plMDBW3qoTZHe8OIrlYJyzJ4Phgb9WMjTO4GL545lH2zZ89M9ux/L27UAtmv9x+77rzmjv0RF8KNNm+Oog5a+0VNR7TO/74gXsrFd8xuiVVaGryLZMCL5B77I4qfnCqSdBeuJGeOf5zG1gEHPYAJpe+lrS/nVAB9LCYnAxAD2NryiBz9tN/4PKeyHz2CUD69Nu4Op4kNMxMbfPsHgN2jgsVY9VpqvSpeJjFIHtFJQBlfEmdtMLOM2taZWLyMbo0DATCTFcr/lqJA+ryDm5qQee+q+m4/vNJvlYgQU32BgAta6HcnfjHiU/aZkCGKflsZH4NIySWSqAChq0/j6rajG9vOmjaMOhevg+8OmFGv1HPfnR0PYWpDOx9rRwsDs2qhUBx5YstvuoDgOo/8PT0vfuaNCPZXGK0ENKtSSUsbTmpzy847ZUIHzdJdjKLSogRZb99IB1If6gpXoxBvUADjsgvmjZ+33fyWtoTC5OcsbfDlq+T37FdAPZcm2wSoyxiLaX+a9gmh61s1gGERRc=
  edge: true
