language: python
python:
  - '3.6'
install:
  - python -m pip install -r requirements.txt
  - python -m pip install -e .[dev]
script:
  - pytest --flake8 --cov=dnote
after_success:
  - coveralls
deploy:
  provider: pypi
  user: yetisir
  password:
    secure: qn6cRHntflM6OZJQf6wShHGuxFjN2Og0ysgWwhG1jrlqWG0ilSZk1ub8or0hdK6wvRgWa+Z8Nb+8fMaJANr51DBMg9QvhD+xdXzyd/3L/2K8g/cFPYYisL4c88/UA0awbiCbQxSqMOLGL7wlBjMyWgckvuN1vMhB2w8RICYF6eK/0PLR8pP8EUlM79wNmkmOD/RSgbrB1b6MpmxuJVtSIZjTMMtwR928+uYFn+t5fxHQAeZUmj12Zoo0Z/XnHe8YyUIviyCSWeHL5+Ff1DiEzeSjdv6mzoTqhANpqA2pNkSfzrmW5sy3495cjHs1BhC2G7ZvWdRlAbpQC4PubwZ/vGpIsdVP0tI8WML33vZzb6VtJEAobgNhondZM385U6tBgjPGxM8k+qFzj6EprF4nc8bvo5tL4XcSplaFH9l4UjJoD1WZekXCLZOotuXOKf65v+vq1y9/GyLTG3RFOK+yp9HLITEMz5C90zVxG0BL3KmO9LmbDJtwKPnVBS0Yb7LgBZqLQFubwv+mRkUc/1C432pL/7nO98FNchOxJM5+u26An0z5xiqfHHBtXlHxZFrJysXX1C/S2q7o63dJdxs/PY0JXsbd+V7VWYIUK5JNaWE1EPT+fMgOinGywxuCUPGuxSafR2cshApAhAlzf/yu50px8TtVET0iHUyandLsZJA=
