site_name: dNote - Cloud Based Note Management
repo_url: https://github.com/yetisir/dnote
site_author: M. Yetisir
site_description: dNote Documentation

nav:
  - Home: index.md

theme: readthedocs

extra:
  social:
    - type: 'github'
      link: 'https://github.com/yetisir/dnote'  
