site_name: cNote - Cloud Based Note Management
repo_url: https://github.com/yetisir/cnote
site_author: M. Yetisir
site_description: cNote Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Implementation: implementation.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash

extra:
  social:
    - type: 'github'
      link: 'https://github.com/yetisir/cnote'  
